 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod'AFNetworking'
pod 'SDWebImage', '~> 4.0'

  # Pods for NYTimes

  target 'NYTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
